name: gaussian_laplacian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.8
  - torch=1.12.1+cu113
  - torchvision=0.13.1+cu113
  - open3d
  - ninja
  - GPUtil
  - opencv-python
  - lpips
  - trimesh
  - tqdm
  - pip=24.0
  - numpy=1.23.4 
  - scipy=1.10.1
  - polyscope
  - robust_laplacian
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - extensions/