name: gaussian_laplacian
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit-dev=11.3
  - python=3.8
  - tqdm
  - numpy=1.23.4 
  - scipy=1.10.1
  - pip
  - plyfile
  - pip:
    - opencv-python
    - open3d
    - ninja
    - GPUtil
    - lpips
    - trimesh
    - polyscope
    - robust_laplacian